#     EX.:009> Faça um programa que leia um numero e mostre sua tabuada na tela.

num=int(input('Digite um número.'))
print(f'A tabua de {num} é :')
print('_' * 10)
print(f'{num} x 1= {num} ')
print(f'{num} x 2= {num*2} ')
print(f'{num} x 3= {num*3} ')
print(f'{num} x 4= {num*4} ')
print(f'{num} x 5= {num*5} ')
print(f'{num} x 6= {num*6} ')
print(f'{num} x 7= {num*7} ')
print(f'{num} x 8= {num*8} ')
print(f'{num} x 9= {num*9} ')
print(f'{num} x 10= {num*10} ')
print('_' * 10)